swagger: '2.0'
info:
  description: Web UI for test rendering [Foremast](https://foremast.readthedocs.io) configurations.
  version: 1.0.0
  title: Foremast UI
  contact:
    email: e4r7hbug@gmail.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  /render/pipeline:
    post:
      tags:
        - pipeline
      operationId: foremast_ui.api.v1.render.pipeline.post
      summary: Render pipeline.json configuration.
      parameters:
        - name: pipeline_json
          in: body
          description: pipeline.json contents to render.
          required: true
          schema:
            type: object
            default:
              owner_email: example@email.com
              notifications:
                slack: '#devchannel'
      responses:
        200:
          description: Return pipeline.json.

definitions:
  pipelineExample:
    type: object
    required:
      - owner_email
    properties:
      owner_email:
        type: string
        default: example@email.com
        example: test@gmail.com
