swagger: '2.0'
info:
  description: Web UI for test rendering [Foremast](https://foremast.readthedocs.io) configurations.
  version: 1.0.0
  title: Foremast UI
  contact:
    email: e4r7hbug@gmail.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
consumes:
  - application/json
produces:
  - application/json
basePath: "/v1"
paths:
  /render_application:
    post:
      summary: Render application.json configuration.
      parameters:
        - name: env
          in: query
          type: string
          required: true
          default: dev
        - name: git_uri
          in: query
          type: string
          required: true
          default: git@github.com:gogoair/foremast.git
        - name: application_json
          in: body
          required: true
          schema:
            $ref: '#/definitions/applicationJson'
      responses:
        200:
          description: Return application.json.
  /render_pipeline:
    post:
      tags:
        - pipeline
      summary: Render pipeline.json configuration.
      parameters:
        - name: pipeline_json
          in: body
          description: pipeline.json contents to render.
          required: true
          schema:
            $ref: '#/definitions/pipelineJson'
      responses:
        200:
          description: Return pipeline.json.

definitions:
  applicationJson:
    type: object
    required:
      - app
    properties:
      app:
        type: object
        required:
          - app_description
          - email
        properties:
          app_description:
            type: string
            example: Test application.
          email:
            type: string
            example: dev@example.com
  pipelineJson:
    type: object
    required:
      - documentation
      - owner_email
      - notifications
    properties:
      documentation:
        type: string
        example: https://foremast.readthedocs.io
      owner_email:
        type: string
        example: example@email.com
      notifications:
        type: object
        properties:
          slack:
            type: string
            example: '#devchannel'
      type:
        type: string
        example: ec2
